//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtributoMuebleTV
    {
        public int idMueble { get; set; }
        public int alto { get; set; }
        public int largo { get; set; }
        public int ancho { get; set; }
        public string colorBase { get; set; }
        public int numSeparaciones { get; set; }
        public int numSepacionesConPuerta { get; set; }
        public int entrepaños { get; set; }
    
        public virtual Mueble Mueble { get; set; }
    }
}
