//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cotizacion()
        {
            this.Mueble = new HashSet<Mueble>();
        }
    
        public int idOrden { get; set; }
        public string documentoExcelProp { get; set; }
        public string PDF { get; set; }
        public string estado { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public System.DateTime fechaeEntrega { get; set; }
        public string correoCliente { get; set; }
        public int idMueble { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mueble> Mueble { get; set; }
    }
}
