//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mueble
    {
        public int idMueble { get; set; }
        public string documentoExcelProp { get; set; }
        public int idOrden { get; set; }
    
        public virtual AtributoLavadero AtributoLavadero { get; set; }
        public virtual AtributoLino AtributoLino { get; set; }
        public virtual AtributoMuebleTV AtributoMuebleTV { get; set; }
        public virtual Cotizacion Cotizacion { get; set; }
    }
}
